# -*- coding: utf-8 -*-
"""gerar_grafos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qTJsDEoZ-hR4RxVH-hf33V0ErXvjBZM
"""

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle

def maior_componente(G):
    componentes = nx.connected_components(G)
    maior = max(componentes, key=len)
    return G.subgraph(maior).copy()

# Padrões de grafos
# g_pad = {'n': 1000, 'p_er': 0.2, 'm_ba':3, 'k_ws': 3, 'p_ws': 0.2}

# Geradores
# def g_ER(n = g_pad['n'], p_er = g_pad['p_er'], **kwargs):
def g_ER(n, p_er): # Change 'p' to 'p_er' to match the keyword used in the call
    G = nx.erdos_renyi_graph(n=n, p=p_er) # Use 'p_er' here as well
    return maior_componente(G)

# def g_BA(n = g_pad['n'], m_ba = g_pad['m_ba'], **kwargs):
def g_BA(n, m_ba): # Add 'm_ba' as a parameter
    G = nx.barabasi_albert_graph(n=n, m=m_ba)
    return maior_componente(G)

# def g_WS(n = g_pad['n'], k_ws = g_pad['k_ws'], p_ws = g_pad['p_ws'], **kwargs):
def g_WS(n, k_ws, p_ws): # Add 'k_ws' and 'p_ws' as parameters
    G = nx.watts_strogatz_graph(n=n, k=k_ws, p=p_ws)
    return maior_componente(G)

# Armazenar linhas
grafos_principais = []

# PAIs principais
print('Principais: n=')
n_list = [500, 1000, 1500, 2000, 2500]
print("ER")
for n in n_list:
  print("-"*50)
  print(f"\nGerando redes de tamanho {n}:")
  for i in range(5):
      grafos_principais.append(('ER', {'n':n}, {'p_er':0.2}, g_ER(n=n, p_er=0.2)))
      grafos_principais.append(('BA', {'n':n}, {'m_ba':3}, g_BA(n=n, m_ba=3)))
      grafos_principais.append(('WS', {'n':n}, {'k_ws':6, 'p_ws':0.2}, g_WS(n=n, k_ws=6, p_ws=0.2)))

len(grafos_principais)

grafos_principais

# Função para extrair os parâmetros do dicionário g_pad, se não estiver no dicionário interno
def extrair_parametros(linha, g_pad):
    dic = linha[1]

    parametros = {
        'g_n': dic.get('n', g_pad['n']),
        'g_p_er': dic.get('p_er', g_pad['p_er']),
        'g_m_ba': dic.get('m_ba', g_pad['m_ba']),
        'g_k_ws': dic.get('k_ws', g_pad['k_ws']),
        'g_p_ws': dic.get('p_ws', g_pad['p_ws'])
    }

    return parametros

dados = []

i = 1
# Processar grafos principais
for grafo_info in grafos_principais:

    graph_type = grafo_info[0]
    # Get the dictionary with 'n'
    n_param_dict = grafo_info[1]
    # Get the dictionary with model-specific parameters
    model_params_dict = grafo_info[2]
    graph_object = grafo_info[3]

    # Combine the parameters from both dictionaries
    g_n = n_param_dict.get('n', None)
    g_p_er = model_params_dict.get('p_er', None)
    g_m_ba = model_params_dict.get('m_ba', None)
    g_k_ws = model_params_dict.get('k_ws', None)
    g_p_ws = model_params_dict.get('p_ws', None)

    dados.append([
        i,             # Index/ID
        graph_type,    # Graph Type (ER, BA, WS)
        g_n,           # n parameter
        g_p_er,        # p_er parameter
        g_m_ba,        # m_ba parameter
        g_k_ws,        # k_ws parameter
        g_p_ws,        # p_ws parameter
        graph_object   # The actual networkx graph object
    ])
    i += 1

dados

arquivo_dados = 'grafos.pkl'

with open(arquivo_dados, 'wb') as f:
    pickle.dump(dados, f)

print("Lista de dados salva com sucesso!")

# Carregar a lista de dados do arquivo
with open(arquivo_dados, 'rb') as f:
    dados_carregados = pickle.load(f)

dados_carregados