# -*- coding: utf-8 -*-
"""gerar_amostras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWgzqk18FwRuNQudddLq6xcXndJuli9d
"""

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
import random
from Custom_Sampling import RWEB, IRWEB, SB, TIES

def maior_componente(G):
    componentes = nx.connected_components(G)
    maior = max(componentes, key=len)
    return G.subgraph(maior).copy()

def medidas(G):

  # Verifica se o grafo tem pelo menos um nó antes de calcular métricas
  if G.number_of_nodes() == 0:
      # Retorna uma série com NaN ou 0s para todas as métricas se o grafo for vazio
      nomes = [
          "grau_medio", "grau_var",
          "path_length_medio", "path_length_var",
          "clustering_medio", "clustering_var",
          "betweenness_medio", "betweenness_var",
          "eigenvector_medio", "eigenvector_var"
      ]
      return pd.Series([np.nan]*len(nomes), index=nomes)


  # Grau-----------------------------------------------------------------------
  graus = np.array([G.degree(node) for node in G.nodes()])
  grau_media = np.mean(graus)
  grau_var = np.var(graus)

### Comprimento médio do menor caminho (average shortest path length) --------
  # Só faz sentido para grafos conectados.
  # Calcula no maior componente para evitar erros em grafos desconectados
  if G.number_of_nodes() > 1: # Precisa de pelo menos 2 nós para ter caminhos
      try:
          # Dicionário com todos os menores caminhos entre pares
          caminhos = dict(nx.all_pairs_dijkstra_path_length(G))
          # Coletando os comprimentos dos menores caminhos
          distancias = []
          for origem, destinos in caminhos.items():
            for destino, distancia in destinos.items():
                if origem != destino:
                    distancias.append(distancia)
          # Média e variância
          path_length_media = np.mean(distancias) if distancias else np.nan # Verifica se há distâncias
          path_length_var = np.var(distancias) if distancias else np.nan
      except Exception as e:
          print(f"Erro ao calcular path length no maior componente: {e}")
          path_length_media, path_length_var = np.nan, np.nan
  else:
      path_length_media, path_length_var = np.nan, np.nan # Se o maior componente tem 0 ou 1 nó


  # Coeficiente de agrupamento (clustering coefficient)------------------------
  clustering = list(nx.clustering(G).values())
  clustering_media = np.mean(clustering) if clustering else np.nan # Verifica se a lista não está vazia
  clustering_var = np.var(clustering) if clustering else np.nan

  # Centralidade de intermediação (betweenness centrality)---------------------
  # Pode ser calculado em grafos desconectados, mas os valores são afetados.
  # Para consistência, podemos considerar apenas o maior componente também.
  # Mantendo no grafo original por enquanto, pois é uma métrica global
  B = dict(nx.betweenness_centrality(G))
  B = list(B.values())
  betweenness_media = np.mean(B) if B else np.nan # Verifica se a lista não está vazia
  betweenness_var = np.var(B) if B else np.nan

  # Centralidade do autovetor (eigenvector centrality) ------------------------
  # Calcula apenas no maior componente conectado para garantir convergência
  av_EC, var_EC = np.nan, np.nan # Inicializa com NaN
  if G.number_of_nodes() > 0:
      try:
          EC = dict(nx.eigenvector_centrality(G, max_iter=5000, tol=1e-06)) # Aumentei as iterações aqui por segurança
          EC = list(EC.values())
          av_EC = np.mean(EC) if EC else np.nan # Verifica se a lista não está vazia
          var_EC = np.var(EC) if EC else np.nan
      except nx.PowerIterationFailedConvergence as e:
          print(f"Eigenvector centrality não convergiu no maior componente: {e}")
          # av_EC e var_EC permanecem como NaN
      except Exception as e:
          print(f"Erro ao calcular eigenvector centrality no maior componente: {e}")
          # av_EC e var_EC permanecem como NaN


  # Vetor final com médias e variâncias
  vetor_resultado = [
      grau_media, grau_var,
      path_length_media, path_length_var,
      clustering_media, clustering_var,
      betweenness_media, betweenness_var,
      av_EC, var_EC
  ]

  nomes = [
      "grau_medio", "grau_var",
      "path_length_medio", "path_length_var",
      "clustering_medio", "clustering_var",
      "betweenness_medio", "betweenness_var",
      "eigenvector_medio", "eigenvector_var"
  ]

  return pd.Series(vetor_resultado, index=nomes)

def medidas_para_dataframe(lista_grafos, nomes=None):
    """
    Recebe uma lista de grafos e retorna um DataFrame com as medidas
    de cada grafo obtidas pela função 'medidas'.

    Parâmetros:
    - lista_grafos: lista de objetos networkx.Graph
    - nomes: lista de nomes (opcional) para os grafos. Se não for passada,
             os índices numéricos serão usados como índices.

    Retorna:
    - DataFrame com uma linha por grafo e colunas com as métricas.
    """
    # Calcula as métricas para cada grafo
    series = [medidas(G) for G in lista_grafos]

    # Cria o DataFrame
    df = pd.DataFrame(series)

    # Define os nomes, se fornecidos
    if nomes:
        df.index = nomes

    return df

# Padrões de amostragens
a_pad = {'k_sb': 3}


def RW(G, max_n, checkpoints, **kwargs):
    return RWEB(G, max_n, checkpoints)

def inducedRW(G, max_n, checkpoints, **kwargs):
    return IRWEB(G, max_n, checkpoints)

def snowball(G, max_n, checkpoints, k=a_pad['k_sb'], **kwargs):
    return SB(G, max_n, checkpoints, k)

def edgeSampling(G, max_n, checkpoints, **kwargs):
    return TIES(G, max_n, checkpoints)

with open('grafos.pkl', 'rb') as f:
    grafos_pais = pickle.load(f)

print(grafos_pais[0:2])
print(len(grafos_pais))

# Lista de algoritmos
algoritmos = [
    RW,
    inducedRW,
    snowball,
    edgeSampling
]

from collections import defaultdict

max_n = 400
checkpoints = [i for i in range(50, 351, 100)]
num_amostras_por_rede = 10

grafos_por_tipo = defaultdict(list)
for linha in grafos_pais: # Altere para `grafos_principais` se for a variável correta
    tipo = linha[1]
    grafos_por_tipo[tipo].append(linha)

df_metricas_amostras = []

print('Calculando métricas das amostras (com checkpoints)...')

# Itere sobre os tipos de redes (ER, BA, WS)
for tipo, lista_grafos in grafos_por_tipo.items():
    print(f'\nTipo de rede: {tipo} ({len(lista_grafos)} grafos)')

    # Itere sobre cada algoritmo de amostragem
    # CUIDADO: Todos os algoritmos em 'algoritmos' precisam ser adaptados para
    # aceitar 'max_n' e 'checkpoint_sizes' e retornar uma lista de grafos.
    # Se você tiver outros algoritmos que não suportam isso, terá que criar uma lógica condicional.
    # Por enquanto, assumimos que 'algo' aqui é 'IRWEB_with_checkpoints'.
    for algo in algoritmos: # Adapte esta linha para seus algoritmos reais
        print(f'  ▶ Algoritmo: {algo.__name__}')

        # Itere sobre cada grafo pai individual
        for linha in lista_grafos:
            id_pai = linha[0]
            G_original = linha[-1] # O objeto grafo original
            n_original_nodes = linha[2]

            for numero_amostra in range(num_amostras_por_rede):
                print(f"    Amostra {numero_amostra + 1}/{num_amostras_por_rede} do grafo {id_pai} ({tipo}) com {algo.__name__}")

                # Chama a função de amostragem uma única vez para este grafo pai e algoritmo,
                # solicitando as amostras nos checkpoints
                try:
                    # O algoritmo deve retornar uma lista de grafos amostrados nos checkpoints
                    list_of_sampled_graphs_at_checkpoints = algo(G=G_original, max_n=max_n, checkpoints=checkpoints, **a_pad)
                except Exception as e:
                    print(f"\n❌ Erro na amostragem com {tipo}-{id_pai}-{algo.__name__}: {e}")
                    continue # Pula para o próximo grafo pai

                # Agora, itere sobre cada grafo de checkpoint retornado e calcule as métricas
                for i, sampled_graph_at_checkpoint in enumerate(list_of_sampled_graphs_at_checkpoints):
                    # O tamanho do checkpoint da caminhada que foi atingido
                    checkpoint_n_walk_nodes = checkpoints[i]

                    # A métrica é calculada no 'sampled_graph_at_checkpoint'
                    try:
                        # 'medidas_para_dataframe' espera uma lista de grafos
                        df_row = medidas_para_dataframe([sampled_graph_at_checkpoint], [f"{tipo}_{algo.__name__}_id{id_pai}_checkpoint{checkpoint_n_walk_nodes}"])
                    except Exception as e:
                        print(f"\n❌ Erro no cálculo das métricas com {tipo}-{id_pai}-{algo.__name__} checkpoint={checkpoint_n_walk_nodes}: {e}")
                        continue # Pula para a próxima amostra de checkpoint

                    # Preenche colunas extras no DataFrame
                    df_row['id_pai'] = id_pai
                    df_row['tipo'] = tipo
                    df_row['algoritmo'] = algo.__name__
                    df_row['numero_amostra'] = numero_amostra + 1
                    df_row['tam_amostra'] = sampled_graph_at_checkpoint.number_of_nodes() # Tamanho real do subgrafo induzido
                    df_row['tam_rede_original'] = n_original_nodes
                    df_row['proporcao_amostra'] = checkpoint_n_walk_nodes / n_original_nodes
                    df_metricas_amostras.append(df_row)

if df_metricas_amostras:
  df_metricas_amostras = pd.concat(df_metricas_amostras).reset_index(drop=True) # drop=True para evitar uma coluna de índice extra
  print('\n✔️ Métricas calculadas com sucesso!')
  df_metricas_amostras.to_csv('metricas_amostras_rede_checkpoints.csv', index=False)
  print('\n✔️ DataFrame salvo como "metricas_amostras_rede_checkpoints.csv" com sucesso!')
else:
  print('\n❌ Não há dados para salvar no DataFrame.')

df_metricas_amostras

grafos_pais_principais = [g for g in grafos_pais if g[1] == 1]

A2 = []

print('A2')
for algo in algoritmos:
    print('\n' + algo.__name__)
    for n in [50, 200]:
        print(n, end=',')
        for linha_pai in grafos_pais_principais:
            id_pai = linha_pai[0]
            G = linha_pai[-1]
            print(linha_pai)
            for _ in range(10):
                A2.append((id_pai, algo.__name__,{'n':n}, algo(G=G, n=n)))


print(f"\nTotal de A2: {len(A2)}")

A3 = []

print('A3')

#RWF
for algo in [RWF]:
    print(algo.__name__)
    for p_rwf in [0.1, 0.3]:
        print(p_rwf, end=',')
        for linha_pai in grafos_pais_principais:
            id_pai = linha_pai[0]
            G = linha_pai[-1]

            for _ in range(10):
                A3.append((id_pai, algo.__name__,{'p_rwf':p_rwf}, algo(G=G, p=p_rwf)))

#SB
for algo in [SB]:
    print(algo.__name__)
    for k_sb in [5, 7]:
        print(k_sb, end=',')
        for linha_pai in grafos_pais_principais:
            id_pai = linha_pai[0]
            G = linha_pai[-1]

            for _ in range(10):
                A3.append((id_pai, algo.__name__,{'k_sb':k_sb}, algo(G=G, k=k_sb)))

#TIES
for algo in [TIES]:
    print(algo.__name__)
    for p_ties in [0.1, 0.3]:
        print(p_ties, end=',')
        for linha_pai in grafos_pais_principais:
            id_pai = linha_pai[0]
            G = linha_pai[-1]

            for _ in range(10):
                A3.append((id_pai, algo.__name__,{'p_ties':p_ties}, algo(G=G, p=p_ties)))


print(f"\nTotal de A3: {len(A3)}")

# Função para extrair os parâmetros do dicionário g_pad, se não estiver no dicionário interno
def extrair_parametros(linha, a_pad):
    dic = linha[2]

    parametros = {
        'a_g_n': dic.get('n', a_pad['n']),
        'a_g_k_sb': dic.get('k_sb', a_pad['k_sb']),
        'a_g_p_rwf': dic.get('p_rwf', a_pad['p_rwf']),
        'a_g_p_ties': dic.get('p_ties', a_pad['p_ties'])
    }

    return parametros

dados = []

i = 1

for grupoA in [A1, A2, A3]:
    for grafo in grupoA:
        parametros = extrair_parametros(grafo, a_pad)
        dados.append([i, grafo[0], grafo[1], parametros['a_g_n'], parametros['a_g_k_sb'], parametros['a_g_p_rwf'], parametros['a_g_p_ties'], grafo[3]])
        i+=1

print(len(dados))
dados[0:3]

arquivo_dados = 'grafos_amostras.pkl'

with open(arquivo_dados, 'wb') as f:
    pickle.dump(dados, f)

print("Lista de dados salva com sucesso!")

# Carregar a lista de dados do arquivo
with open(arquivo_dados, 'rb') as f:
    dados_carregados = pickle.load(f)

dados_carregados[0:2]

